name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install poetry
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          make poetry

      - name: Build dependencies
        run: poetry install

      - name: Deploy docs
        run: |
          poetry shell
          mkdocs gh-deploy