name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - synchronize # This occurs when a source branch of a PR receives a new commit
      - reopened

jobs:
  do_this:
    name: Show
    runs-on: ubuntu-latest

    steps:
      - name: Show vars
        run: |
          echo "${GITHUB_REF}"
